apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ .Values.global.serviceAccount }}
  labels:
    app: {{ .Values.global.serviceAccount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.serviceAccount }}-rbac-{{ template "namespace" . }}
  labels:
    app: {{ .Values.global.serviceAccount }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.serviceAccount }}
    namespace: {{ template "namespace" . }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
