global:
  registry: 192.168.1.240
  repository: beluga
  serviceAccount: cicd-webserver-sa

cicdWebserver:
  replicaCount: 1
  imageTag: develop
  port: 8080
  serviceType: NodePort

database:
  address: 192.168.1.99
  port: 3306
  username: root
  password: root
  databaseName: beluga
  logLevel: 4
